CO-3086 CO-3086 module is migrated and installable
CompassionCH/compassion-switzerland pull request #1022
Opened 2020-02-19 10:44 UTC by quentingigon

2020-02-19 10:55 UTC, quentingigon commented
TODO: change oca_dependencies to add mail_sendgrid_mass_mailing to social

2020-02-27 12:42 UTC, quentingigon commented
waiting for the fix for sms_939 from JosueBulle

2020-03-04 13:12 UTC, ecino requested changes

2020-03-04 13:12 UTC, ecino commented on oca_dependencies.txt
> +social https://github.com/quentingigon/social sendgrid_and_mass_mailing_migrations
You can change this as we created a branch on CompassionCH
```suggestion
social https://github.com/CompassionCH/social 11.0-mig-mail_sendgrid_mass_mailing
```

2020-03-04 13:12 UTC, ecino commented on mass_mailing_switzerland/models/mass_mailing.py
> +    #                      'You have to choose a new slug for each mailing !')]
Why removing this?

2020-03-04 13:12 UTC, ecino commented on mass_mailing_switzerland/migrations/10.0.2.1.2/pre-migration.py
> -# -*- coding: utf-8 -*-
You can remove the migrations folder

2020-03-04 14:58 UTC, ecino requested changes

2020-03-04 14:58 UTC, ecino commented on mass_mailing_switzerland/models/mass_mailing.py
>                           'You have to choose a new slug for each mailing !')]
In fact I checked and this field was removed! So you can remove the constraint as you did before, sorry.

2020-03-05 08:14 UTC, ecino commented
flake8 errors :
```
mass_mailing_switzerland/models/mass_mailing.py:14:1: E303 too many blank lines (3)
website_event_compassion/forms/agreement_step2_forms.py:10:1: F401 'datetime.datetime' imported but unused
```

2020-03-05 08:27 UTC, ecino commented
Please rebase the branch to fix the conflicts.

2020-03-05 09:52 UTC, ecino approved these changes

2020-03-05 09:53 UTC, merged