Co 3084     Migrer account_reconcile_compassion
CompassionCH/compassion-switzerland pull request #1024
Opened 2020-02-19 12:43 UTC by SylvainLosey

2020-02-26 14:20 UTC, josueBulle requested changes

2020-02-26 14:20 UTC, josueBulle commented on account_reconcile_compassion/models/res_config.py
> +    _inherit = "account.config.settings"
'account.config.settings' should not exist.
This class should _inherit 'res.config.settings' and override the `get_values` and `set_values` methods.
Views need adaptations

2020-02-26 14:20 UTC, josueBulle commented on account_reconcile_compassion/models/res_config.py
>      def set_currency_exchange_analytic_account(self):
The `set_currency...` and `get_currency...` methods can be deleted.
Calls to `get_currency_` will then need refactoring

2020-02-26 14:31 UTC, josueBulle commented
Please check your PR on the OCA too, tests are failing.

2020-03-04 13:20 UTC, ecino commented
Please make PR of OCA on the fork from CompassionCH. Then update oca_dependencies.txt to fetch the CompassionCH fork so that the requirement can be found.

2020-03-05 08:15 UTC, ecino requested changes

2020-03-05 08:15 UTC, ecino commented on oca_dependencies.txt
> +bank-statement-import https://github.com/CompassionCH/bank-statement-import 11.0
Sorry, I changed the branch name to make it more clear.
```suggestion
bank-statement-import https://github.com/CompassionCH/bank-statement-import 11.0-camt-details
```

2020-03-05 08:17 UTC, ecino commented
Flake8 error: `website_event_compassion/forms/agreement_step2_forms.py:10:1: F401 'datetime.datetime' imported but unused`

Please correct as well the test `File "/home/travis/build/CompassionCH/compassion-switzerland/account_reconcile_compassion/tests/test_bank_account_assignation.py", line 26, in setUp
`     "journal_id": self.env.ref("l10n_ch_lsv_dd.lsv_account_journal").id,`

The module lsv_dd doesn't exist anymore so you cannot reference this anymore. You should use another demo journal instead.

2020-03-05 08:26 UTC, ecino commented
Please rebase onto 11.0 to fix the conflicts

2020-03-05 09:55 UTC, ecino commented
Tests are still failing.

2020-03-05 11:33 UTC, SylvainLosey commented
```
# test get_move_lines_for_reconciliation method
self.assertEqual(len(bank_statement_line.get_move_lines_for_reconciliation()), 12)
```

This was previously asserting that it was equal to 0, which by reading the related functions I don't understand.

2020-03-05 14:00 UTC, closed without merging