Deactivate thankyou letters
CompassionCH/compassion-switzerland pull request #1099
Opened 2020-06-04 13:40 UTC by quentingigon

Half of fix for reconcile view. Second half made on compassion-modules

2020-06-04 13:42 UTC, quentingigon commented
other half is [HERE](https://github.com/CompassionCH/compassion-modules/pull/1342)

2020-06-08 07:43 UTC, ecino requested changes

2020-06-08 07:43 UTC, ecino commented on account_reconcile_compassion/models/account_reconcile_model.py
> +    no_notifications = fields.Boolean(
Please rename the field like proposed in other PR. Also add the help parameter.

2020-06-08 08:53 UTC, ecino requested changes

2020-06-08 08:53 UTC, ecino commented on account_reconcile_compassion/models/bank_statement_line.py
> +            "avoid_mobile_donation_notification": mv_line_dicts[0]['avoid_mobile_donation_notification']
```suggestion
            "avoid_mobile_donation_notification": mv_line_dicts[0][
                'avoid_mobile_donation_notification']
```

2020-06-08 10:05 UTC, ecino approved these changes

2020-06-08 10:06 UTC, merged