CO-3214 replaced language of gift BVR from partner's to correspondent's
CompassionCH/compassion-switzerland pull request #1153
Opened 2020-07-08 13:41 UTC by wvmrtn

When printing gift payment slips, switched language from the partner's to the correspondent's.

2020-07-16 14:18 UTC, Theyiot reviewed
LGTM

2020-07-23 09:29 UTC, ecino requested changes

2020-07-23 09:29 UTC, ecino commented on report_compassion/models/contract.py
> +        lang = self.correspondent_id.lang
In fact the gift could be either sent to the payer or the correspondent. There is a field in the contract determining this and you could use it to use the correct partner.
```suggestion
        lang = self.mapped(self.send_gifts_to).lang
```

2020-07-28 07:48 UTC, Theyiot commented
Required modifications were applied, the _PR_ is now ready.

2020-07-28 08:44 UTC, merged