CO-3431 Amount on payment slip and scan_line is now the right amount
CompassionCH/compassion-switzerland pull request #1219
Opened 2020-08-20 09:14 UTC by Theyiot

2020-09-01 12:00 UTC, ecino requested changes
You should add a migration script to force reload `report_compassion/report/bvr_sponsorship.xml`

2020-09-11 07:36 UTC, ecino commented
I think you forgot this PR.

2020-09-11 08:42 UTC, Theyiot commented
> I think you forgot this PR.

You're right ;) The script has now been added

2020-09-11 08:43 UTC, ecino approved these changes

2020-09-11 08:43 UTC, merged