CO-3594: -Added a new subsection "My sponsorship" in "My Financials".
CompassionCH/compassion-switzerland pull request #1311
Opened 2021-04-07 06:08 UTC by coup1234

2021-04-09 11:47 UTC, JonathanGuerne commented on website_compassion/template/my_account_donations.xml
> +<!--                      <div class="row">-->
avoid leaving comments in published code

2021-04-09 11:47 UTC, JonathanGuerne commented on website_compassion/template/my_account_donations.xml
> +<!--               </div>-->
comment not needed

2021-04-09 11:47 UTC, JonathanGuerne commented on website_compassion/template/my_account_donations.xml
> +                          <a t-attf-href="/my/donations/update?recurring_contract=#{sponsor.id}" class="btn btn-primary">Upgrade to 50 <t t-esc="sponsor.invoice_line_ids[0].currency_id.name"/></a>
If selected sponsorship < 42 CHF the upgrade wouldn't be all the way to 50 (with current implementation). 
Maybe a bit confusing for the end user ?

2021-04-09 11:47 UTC, JonathanGuerne commented on website_compassion/controllers/my_account.py
> +            .filtered(lambda a: a.state not in ["cancelled", "terminated"])
Same as above
`contracts_correspondant` refers to contracts where current partner doesn't pay. `contracts_paid` seems more appropriate

2021-04-09 11:47 UTC, JonathanGuerne commented on website_compassion/controllers/my_account.py
> +                    + partner.contracts_correspondant) \
`contracts_correspondant` refers to contracts where current partner doesn't pay. `contracts_paid` seems more appropriate

2021-04-09 11:47 UTC, JonathanGuerne commented on website_compassion/template/my_account_donations.xml
> +               <center> Comfirm upgrade to 50 CHF ? </center>
Same as above
If selected sponsorship < 42 CHF the upgrade wouldn't be all the way to 50 (with current implementation).
Maybe a bit confusing for the end user ?

2021-04-09 11:47 UTC, JonathanGuerne commented on website_compassion/controllers/my_account.py
> +            lambda a: int(a.id) == int(recurring_contract))
Potential error when `recurring_contract` is not specified. Add redirection if None ?
a.id is already an int

2021-04-16 09:52 UTC, ecino requested changes

2021-04-16 09:52 UTC, ecino commented on website_compassion/controllers/my_account.py
> +    @route("/my/donations/update", type="http", auth="user", website=True)
```suggestion
    @route("/my/donations/upgrade", type="http", auth="user", website=True)
```

2021-04-16 09:52 UTC, ecino commented on website_compassion/controllers/my_account.py
> +            lambda a: int(a.id) == int(recurring_contract))
This is useless computations and filtering.
```suggestion
        contract = request.env["recurring.contract"].browse(int(recurring_contract))
```

2021-04-16 09:52 UTC, ecino commented on website_compassion/controllers/my_account.py
> +        if int(contract.total_amount) > 42:
```suggestion
        if int(contract.total_amount) > 42 or contract.state in ("cancelled", "terminated"):
```

2021-04-16 09:54 UTC, ecino commented on website_compassion/template/my_account_donations.xml
> +                          <a t-attf-href="/my/donations/update?recurring_contract=#{sponsor.id}" class="btn btn-primary">Upgrade to 50 <t t-esc="sponsor.invoice_line_ids[0].currency_id.name"/></a>
```suggestion
                          <a t-attf-href="/my/donations/upgrade?recurring_contract=#{sponsor.id}" class="btn btn-primary">Upgrade to 50 <t t-esc="sponsor.invoice_line_ids[0].currency_id.name"/></a>
```

2021-04-16 09:54 UTC, ecino commented on website_compassion/template/my_account_donations.xml
> +                    <a t-attf-href="/my/donations/update?res=refused&amp;recurring_contract=#{sponsor}" class="btn btn-primary">No</a>
```suggestion
                    <a t-attf-href="/my/donations/upgrade?res=accepted&amp;recurring_contract=#{sponsor}" class="btn btn-primary">Yes</a>
                    <a t-attf-href="/my/donations/upgrade?res=refused&amp;recurring_contract=#{sponsor}" class="btn btn-primary">No</a>
```

2022-02-21 08:14 UTC, closed without merging