CO-3487: Make donate direct form
CompassionCH/compassion-switzerland pull request #1313
Opened 2021-04-07 06:58 UTC by coup1234

- New gift form directly in Odoo replacing redirection on the compassion website.
- Button in 'gift history', make a donation
- Make a donation button appears without any previous gift.

2021-04-09 12:36 UTC, JonathanGuerne commented on website_compassion/template/my_account_my_children.xml
> +            <a t-if="state == 'active'" class="btn btn-primary" t-attf-href="/my/children/donate?child_id={{child_id.id}}" target="_blank"><span>Make a donation</span></a>
```suggestion
            <a t-if="state == 'active'" class="btn btn-primary" t-attf-href="/my/children/donate?child_id={{child_id.id}}" ><span>Make a donation</span></a>
```
Opening a new tab might not be necessary

2021-04-09 12:36 UTC, JonathanGuerne commented on website_compassion/forms/child_donation_form.py
> +    return valu.filtered(lambda a: int(a.child_id) == int(child.id))
```suggestion
    return valu.filtered(lambda a: a.child_id == child.id)
```

2021-04-09 12:36 UTC, JonathanGuerne commented on website_compassion/forms/child_donation_form.py
> +    :param filter_fun: optional filter function
update docstring

2021-04-09 12:36 UTC, JonathanGuerne commented on website_compassion/template/my_account_my_children.xml
> +            <hr/>
small comment: `<hr/>` (and following) could be indented

2021-04-09 12:36 UTC, JonathanGuerne commented on website_compassion/template/my_account_my_children_donate.xml
> +                    <h3>Make a gift to <t t-esc="child_id.preferred_name"/></h3>
```suggestion
                    <h3>donation_form.form_title()</h3>
```
To keep all the code in one place you could define the form title directly in python (there is also a form_description if needed)

2021-04-09 12:36 UTC, JonathanGuerne commented on website_compassion/forms/child_donation_form.py
> +
```suggestion
    @property
    def form_title(self):
        return _("Gift to ...")
```
mentioned in template. Could be use to keep all Data in one place

2021-04-09 12:36 UTC, JonathanGuerne commented on website_compassion/forms/child_donation_form.py
> +#    @author: Emanuel Cino <ecino@compassion.ch>
Give yourself some credit :tada:

2021-04-16 10:01 UTC, ecino requested changes

2021-04-16 10:01 UTC, ecino commented on website_compassion/forms/child_donation_form.py
> +    ]
This is wrong, it would mean these fields are stored in the "res.partner" model.
```suggestion
```

2021-05-07 07:55 UTC, JonathanGuerne approved these changes

2023-02-20 13:15 UTC, closed without merging