CO-3575 add link to download bvr for children gift and sponsorship
CompassionCH/compassion-switzerland pull request #1317
Opened 2021-04-08 13:30 UTC by JonathanGuerne

- add link in my/donation to download bvr for sponsorship (1 bvr for all sponsorships)
- add link in my/children to download bvr for gift to a specific children

2021-04-08 13:42 UTC, JonathanGuerne commented
Move the PR to draft to resolve issue with blank sponsorship BVR. Link to download BVR should only be visible if a `bvr_reference` is linked to the specified `contract_group`

2021-04-16 10:04 UTC, ecino requested changes

2021-04-16 10:04 UTC, ecino commented on website_compassion/template/my_account_donations.xml
> +                            <t t-set="input_value">Download a BVR</t>
```suggestion
                            <t t-set="input_value">Download sponsorship payment slips</t>
```

2021-04-16 10:04 UTC, ecino commented on website_compassion/template/my_account_my_children.xml
> +                <a t-if="state == 'active'" class="btn btn-primary" t-attf-href="/my/download/gift_bvr?child_id={{child_id.id}}"><span>Download a BVR</span></a>
```suggestion
                <a t-if="state == 'active'" class="btn btn-primary" t-attf-href="/my/download/gift_bvr?child_id={{child_id.id}}"><span>Download payment slips for gifts</span></a>
```

2021-04-16 13:06 UTC, ecino approved these changes

2021-04-16 13:07 UTC, merged