CO-3727 migration to prevent duplicate ref
CompassionCH/compassion-switzerland pull request #1395
Opened 2021-08-09 12:52 UTC by JonathanGuerne

2021-08-09 13:58 UTC, ecino requested changes
- Did you test the migration? How many manual migration did you encounter?
- Could you as well remove the duplicate sequence partner.ref in the migration?

2021-08-09 13:58 UTC, ecino commented on partner_compassion/migrations/12.0.1.1.4/post-migration.py
> +    sponsor_to_change = partner_to_change.filtered(lambda p: any(p.mapped("sponsorship_ids.is_active")))
I wonder if this works as well?
```suggestion
    sponsor_to_change = partner_to_change.filtered("sponsorship_ids.is_active")
```

2021-08-09 14:13 UTC, JonathanGuerne commented
I tested it on my local database (which is about 2 month old now). I ended up with < 10 case that needed a manual inspection. 
Strange thing was that concerned partner had no parent_id. It seems to be an issue with the duplicated ref entry.

2021-08-09 14:15 UTC, JonathanGuerne commented on partner_compassion/migrations/12.0.1.1.4/post-migration.py
> +    sponsor_to_change = partner_to_change.filtered(lambda p: any(p.mapped("sponsorship_ids.is_active")))
it does !

2021-08-10 12:02 UTC, JonathanGuerne commented
As asked I've remove the unwanted `ir.sequence`. It required me to alter the `ir_model_data` table

There are 2 entries that match the following condition : 
```sql 
model = 'ir.sequence' and name = 'sequence_partner_ref'
```
Each entry point to a different module. 

If we don't alter this table removing the unwanted sequence will trigger it's recreation. 

I chose to change the `res_id` of one of the entry to copy the other one (base on which one seemed to be used by our system).

2021-08-12 11:53 UTC, ecino approved these changes

2021-08-12 11:53 UTC, merged