CO-3869 Some people don't receive the zoom link
CompassionCH/compassion-switzerland pull request #1453
Opened 2022-01-20 14:40 UTC by TheRaphael0000

2022-01-20 16:22 UTC, TheRaphael0000 commented
To test and use my changes, please update the zoom automated action as following :

![image](https://user-images.githubusercontent.com/15734398/150378949-7f6fefc5-65eb-48fa-8515-02da3ae5ecc9.png)

2022-01-25 14:21 UTC, ecino requested changes

2022-01-25 14:21 UTC, ecino commented on partner_communication_switzerland/models/res_partner_zoom_attendee.py
> +    @api.one
api.one is deprectated and should not be used. but if you are sure you always call this method with a single record you can start the method with `self.ensure_one`

2022-01-25 14:21 UTC, ecino commented on partner_communication_switzerland/models/res_partner_zoom_attendee.py
> +        config_id = self.env.ref(config_name.value).id
Let's make it clear that we should only call this method on a single record.
```suggestion
        self.ensure_one()
        config_id = self.env.ref(config_name.value).id
```

2022-01-25 14:46 UTC, ecino approved these changes

2022-01-25 14:46 UTC, merged