mass_mailing_contact refactor
CompassionCH/compassion-switzerland pull request #1491
Opened 2022-02-18 14:28 UTC by TheRaphael0000

replace patrner_id by a computed field, a override a few function and fields by computed fields

2022-02-23 09:38 UTC, ecino requested changes

2022-02-23 09:38 UTC, ecino commented on mass_mailing_switzerland/models/mass_mailing_contact.py
> +    )
Can be a simple related field:
```suggestion
    name = fields.Char(related="partner_id.name")
```

2022-02-23 09:38 UTC, ecino commented on mass_mailing_switzerland/models/mass_mailing_contact.py
> +    )
```suggestion
    country_id = fields.Many2one(related="partner_id.country_id")
```

2022-02-23 09:38 UTC, ecino commented on mass_mailing_switzerland/models/mass_mailing_contact.py
> +        readonly=True,
Those are default values and can be omitted.
```suggestion
```

2022-02-23 09:38 UTC, ecino commented on mass_mailing_switzerland/models/mass_mailing_contact.py
> +    )
```suggestion
    company_name = fields.Char(related="partner_id.company_name")
```

2022-02-23 09:38 UTC, ecino commented on mass_mailing_switzerland/models/mass_mailing_contact.py
> +        readonly=True,
```suggestion
```

2022-02-23 09:38 UTC, ecino commented on mass_mailing_switzerland/models/mass_mailing_contact.py
> +        readonly=True,
```suggestion
    tag_ids = fields.Many2many(related="partner_id.tag_ids"
```

2022-02-23 11:50 UTC, TheRaphael0000 commented on mass_mailing_switzerland/models/mass_mailing_contact.py
> +        readonly=True,
I'm not sure for this one

2022-02-23 11:58 UTC, TheRaphael0000 commented on mass_mailing_switzerland/models/mass_mailing_contact.py
> +        readonly=True,
This doesn't work either :
```
    tag_ids = fields.Many2many(related="partner_ids.category_id")
```

2022-02-23 11:59 UTC, TheRaphael0000 commented on mass_mailing_switzerland/models/mass_mailing_contact.py
> +        readonly=True,
The first solution allows to have the union the partner tags, instead of the tag of the main one

2022-02-24 07:22 UTC, ecino approved these changes

2022-02-24 07:24 UTC, merged