14.0 t0290
CompassionCH/compassion-switzerland pull request #1582
Opened 2024-02-26 14:44 UTC by auclerc

2024-03-07 09:45 UTC, ecino commented on partner_compassion/models/partner_compassion.py
> +        all_phone_destination_codes = [
Where does this list come from? Maybe a comment would be helpful here.

2024-03-07 09:45 UTC, ecino commented on partner_compassion/models/partner_compassion.py
> +        all_mobile_destination_codes = [74, 75, 76, 77, 78, 79]
Where does it come from?

2024-03-07 10:01 UTC, ecino requested changes

2024-03-07 10:01 UTC, ecino commented on partner_compassion/models/partner_compassion.py
> +        if phone:
Maybe we should also check if the partner country is switzerland before doing the check. We may sometimes create partners from other countries that may have a different phone format. Or we can maybe validate the phone for any country with the phonenumbers library?

2024-03-07 10:01 UTC, ecino commented on partner_compassion/models/partner_compassion.py
> +        if mobile:
Same remark about checking the country.

2024-03-07 10:01 UTC, ecino commented on partner_compassion/models/partner_compassion.py
> +            phone_national_destination_code = int(str(parsed_phone.national_number)[:2])
I don't understand why you need such conversions. What is the format of `parsed_phone.national_number`?

2024-03-07 10:01 UTC, ecino commented on partner_compassion/models/partner_compassion.py
> +                if not mobile:
Why is this `if` needed, shouldn't we remove the `phone` value in any case, if it's moved in the `mobile` field?

2024-03-07 10:01 UTC, ecino commented on partner_compassion/models/partner_compassion.py
> +                    vals["mobile"] = False
Maybe we should better check if a `phone` value is already set and not override it, and also check that we didn't move the `phone` field value and avoid deleting it afterward (you should introduce the bool var for that purpose).
```suggestion
                if not vals.get("phone"):
                    vals["phone"] = mobile
                    if not phone_moved_to_mobile:
                        vals["mobile"] = False
```

2024-03-07 10:01 UTC, ecino commented on partner_compassion/models/partner_compassion.py
> +
The return is not needed, the dictionary is modified in place.

2024-03-14 13:39 UTC, auclerc commented on partner_compassion/models/partner_compassion.py
> +            phone_national_destination_code = int(str(parsed_phone.national_number)[:2])
To use the .is_valid_number(), we have to use a parsed number.

2024-03-14 13:39 UTC, auclerc commented on partner_compassion/models/partner_compassion.py
> +                if not mobile:
Yes, correct

2024-03-19 10:17 UTC, ecino requested changes

2024-03-19 10:17 UTC, ecino commented on partner_compassion/models/partner_compassion.py
> +        if vals.get('country_id') == 43 or self.country_id == 43:
```suggestion
        swiss_country = self.env.ref("base.ch")
        if vals.get('country_id') == swiss_country.id or self.mapped("country_id") == swiss_country:
```

2024-03-19 10:17 UTC, ecino commented on partner_compassion/models/partner_compassion.py
> +                    # if not mobile:
```suggestion
```

2024-03-19 13:24 UTC, ecino commented
Thank you, I merged manually (for fixing conflicts).

2024-03-19 13:24 UTC, closed without merging