T1702 - Donations communication test cases
CompassionCH/compassion-switzerland pull request #1647
Opened 2024-08-19 12:37 UTC by clementcharmillot

2024-08-19 12:46 UTC, ecino commented
Wouldn't it be better to apply a domain to the partner field so that the user can only select partners that have move lines ? Because with your solution, we will select a partner for testing and then the generated communication will be for another one, which will be confusing.

2024-08-20 09:30 UTC, clementcharmillot commented
I've implemented your suggestion for the default random selection of a partner. 
But for the partner input, instead of filtering partners, I display an error if the manually picked partner has no invoice of type fund. As a partner having such invoice is not obvious, it might be confusing if it simply doesn't appear in search without explanation when we are searching for a specific one.
Let me know if you'd prefer the other approach.

2024-08-22 06:08 UTC, ecino requested changes
OK, but the error message will be more explicit to our staff like that.

2024-08-22 06:08 UTC, ecino commented on partner_communication_switzerland/models/partner_communication_config.py
> +                        "requires one. Please, pick a partner with an invoice line."
```suggestion
                        "The selected partner is not a donor but this test case "
                        "requires one. Please, pick a donor."
```

2024-08-22 07:00 UTC, merged