T0024 - Automatic reminder for invalid partners
CompassionCH/compassion-switzerland pull request #1663
Opened 2024-09-19 06:49 UTC by Gordack

A scheduled action should be created, similar to : 
![image](https://github.com/user-attachments/assets/67afd475-7052-494c-a4b1-2553d77554c2)

After test with MailHog, the following output is obtained : 
![image](https://github.com/user-attachments/assets/9d27e29e-e637-4e72-b45f-5cf621c959e3)

2024-09-24 05:42 UTC, ecino requested changes
One small remark and another general question : Could we simply automatically archive the found contacts (and still send the notification email to SDS)? Then in the email we could simply write: "Those following contacts were found and automatically archived". That means writing {"archive": True} on them.

2024-09-24 05:42 UTC, ecino commented on partner_communication_switzerland/data/auto_reminder_archive_contact.xml
> +                        <p>ID ${partner.id} - ${partner.name}</p>
I think that the partner reference is more meaningful to SDS than the database ID. You could also include a direct link to the contact:
```suggestion
                        <p><a href="/web#id=${partner.id}&model=res.partner&view_type=form&menu_id=1744">Ref ${partner.ref} - ${partner.name}</a></p>
```

2024-09-26 05:14 UTC, Gordack commented
> One small remark and another general question : Could we simply automatically archive the found contacts (and still send the notification email to SDS)? Then in the email we could simply write: "Those following contacts were found and automatically archived". That means writing {"archive": True} on them.

When I discussed that with Sarah, she was not so happy about the idea of automating the archive part, because she was scared that Odoo would archive people that should not be archived. Therefore, when we discussed that with Andre, we choose to not automatically archive first, in order to let SDS check that the people we propose to archive are the good ones. But yes, if SDS is happy with how the criteria are set, it would be better to archive the people that need to be archived automatically.

2024-09-26 13:39 UTC, ecino commented
Waiting Sarah's feedback in order to know whether we should directly archive those contacts or not.

2024-10-11 13:18 UTC, nlachat-compassion commented
> Waiting Sarah's feedback in order to know whether we should directly archive those contacts or not.

@ecino I'm taking over this task. So in the end, we should **not** automatically archive the invalid partners, correct? Only send an email reminder with the list of potentially invalid partners?

2024-10-11 14:38 UTC, ecino commented
@nlachat-compassion exactly

2024-10-15 13:05 UTC, nlachat-compassion commented
What I did until now:
- Add xml definition for the cron job which sends the reminder (configured to send once a week)
- Add a link to the task T0024 as a reference for the criteria which define a partner as invalid in the email reminder
- Pass the list of invalid partners through the context in the email template in order to avoid computing it twice. This requires a modification to another repo: https://github.com/CompassionCH/compassion-modules/pull/1979 , which should be merged **before** this one.

@ecino what do you think about my proposed implementation?

2024-11-18 11:05 UTC, ecino commented
@nlachat-compassion This seems ok for me. Did you test without the modification in compassion-modules? I have the feeling the context should be passed even without the other change.

2024-11-19 14:47 UTC, nlachat-compassion commented
> @nlachat-compassion This seems ok for me. Did you test without the modification in compassion-modules? I have the feeling the context should be passed even without the other change.

Ah yes, indeed @ecino it works without the change to `compassion-modules`. I think I probably forgot to update the view at some point and I thought that the context was not passed properly.

2024-11-19 15:09 UTC, ecino approved these changes

2024-11-19 15:09 UTC, merged