CO-1452 - Compatibility between hr_attendance_calendar and hr_switzerland
CompassionCH/compassion-switzerland pull request #354
Opened 2018-02-21 12:46 UTC by samuel-fringeli

2018-02-23 08:28 UTC, eicher31 requested changes

2018-02-23 08:28 UTC, eicher31 commented on hr_switzerland/models/hr_employee.py
> +                current_att_day.worked_hours - current_att_day.due_hours
current_att_day.worked_hours doesn't return the current time elapsed, you need the previously method used for compute the employe.today_hour

2018-02-23 08:28 UTC, eicher31 commented on hr_switzerland/models/hr_employee.py
> +                employee._convert_hour_to_time(math.fabs(employee.extra_hours))
You can replace math.fabs by abs() without import (to verify)

2018-02-26 15:28 UTC, ecino commented
@eicher31 are you ok with this pull request?

2018-02-27 06:09 UTC, eicher31 approved these changes

2018-02-27 06:11 UTC, eicher31 commented
pep8 error
partner_communication_switzerland/migrations/10.0.2.4.1/post-migration.py:19:1: E302 expected 2 blank lines, found 1

2018-02-27 07:54 UTC, ecino requested changes
Please fix it with PEP8 error. Thanks

2018-02-27 07:54 UTC, ecino commented on partner_communication_switzerland/migrations/10.0.2.4.1/post-migration.py
> +# on doit pouvoir faire en sorte que les mails déjà existants à qui on a envoyé
Please write comments in English, as it is hosted and public on github.

2018-02-28 10:26 UTC, ecino approved these changes

2018-02-28 10:27 UTC, merged