Fixes for odoo pylint
CompassionCH/compassion-switzerland pull request #389
Opened 2018-03-23 08:30 UTC by vwvw

Fixes for a lot of pylint issues comming up in travis. 

Added blank lines at end of files.
Created ReadMe.rst
Fixed local imports
Changed tab format.

2018-03-23 16:09 UTC, ecino commented
Good job, but there are still some errors :(

2018-03-26 15:53 UTC, vwvw commented
Yeah, but for the other errors we need to discuss to see what's wrong ;-)

2018-04-03 14:31 UTC, ecino commented
Tests are failing. Conflicts with latest changes.

2018-04-04 09:50 UTC, ecino commented
Pylint is good now but something must be broken, the tests are failing :
```
ailed to initialize database `openerp_test`.
Traceback (most recent call last):
  File "/home/travis/odoo-10.0/odoo/service/server.py", line 911, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/travis/odoo-10.0/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/travis/odoo-10.0/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/home/travis/odoo-10.0/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/travis/odoo-10.0/odoo/modules/loading.py", line 136, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/home/travis/odoo-10.0/odoo/modules/registry.py", line 318, in init_models
    model.init()
  File "/home/travis/build/CompassionCH/compassion-switzerland/sponsorship_switzerland/reports/sponsorships_evolution_months_report.py", line 72, in init
    self.env.cr.execute(query, params)
  File "/home/travis/odoo-10.0/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/travis/odoo-10.0/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "'sponsorships_evolution_months_report'"
LINE 2:             CREATE OR REPLACE VIEW 'sponsorships_evolution_m...
                                           ^
```

2018-04-06 13:46 UTC, vwvw commented
Travis is green !

2018-04-09 06:58 UTC, ecino requested changes
It's a historical day for Travis ;)

2018-04-09 06:58 UTC, ecino commented on partner_communication_switzerland/views/recurring_contracts_view.xml
> +    <record id="invoice_line_inherit_muskathlon" model="ir.ui.view">
All those muskathlon records have been moved to the module `muskathlon`. You can remove them

2018-04-09 06:58 UTC, ecino commented on pgsql_auto_backup/i18n/bg.po
> +#: model:ir.model,name:auto_backup.model_DbBackup
I think this is a bad search/replace... you can undo your changes in the .po files

2018-04-09 07:59 UTC, ecino approved these changes

2018-04-09 07:59 UTC, merged