C-2060 BVR ref is created at initialization
CompassionCH/compassion-switzerland pull request #642
Opened 2018-10-02 10:11 UTC by quentingigon

2018-10-02 14:06 UTC, ecino requested changes

2018-10-02 14:06 UTC, ecino commented on sms_939/models/recurring_contract_group.py
> +    def onchange_payment_mode_id(self):
This method already exists here : https://github.com/CompassionCH/compassion-switzerland/blob/10.0/sponsorship_switzerland/models/contract_group.py#L149

You can delete this file.

2018-10-02 14:06 UTC, ecino commented on sms_939/models/recurring_contract.py
> +from odoo.exceptions import UserError
this change is not needed

2018-10-02 14:06 UTC, ecino commented on sms_939/models/__init__.py
>  from . import recurring_contract
In the model recurring_contract you should inherit the method `associate_group` and call the method `on_change_payment_mode` from there.

2018-10-02 14:06 UTC, ecino commented
Please rebase onto compassion/devel and fix conflicts

2018-10-03 06:38 UTC, quentingigon commented
I dont know if the problem comes from my modification but when testing I found that when we use an existant partner for an SMS request, the first time we complete the second form fails (but with no error message) and no children is assigned to the partner. If we redo the form, everything is working as intended. This does not happen with a partner just created

2018-10-03 11:41 UTC, ecino approved these changes

2018-10-03 11:41 UTC, merged