CO-2488 Ending sponsorship communication
CompassionCH/compassion-switzerland pull request #860
Opened 2019-04-15 10:06 UTC by joblo-compassion

add a variation about ending
 -> if an activated sponsorship end and is not cancelled
    it's a terminated communication that is send

2019-04-15 14:06 UTC, joblo-compassion commented
Just not sure if  "partner_communication_switzerland.planned_completion" is the good template

also I didnt know of to run a test of the reprise sponsorships to check the three options there.
```
    cancellation = self.env.ref(
    'partner_communication_switzerland.sponsorship_cancellation')
    completion = self.env.ref(
    'partner_communication_switzerland.planned_completion')
    no_sub = self.env.ref(
    'partner_communication_switzerland.planned_no_sub')
```

but the change is small, so check should be easy

2019-04-17 13:06 UTC, ecino requested changes
Everything is good, but it's just another communication that is used.

2019-04-17 13:06 UTC, ecino commented on partner_communication_switzerland/models/contracts.py
> +            'partner_communication_switzerland.planned_completion')
```suggestion
            'partner_communication_switzerland.sponsorship_cancellation')
```

2019-04-17 13:06 UTC, ecino commented on partner_communication_switzerland/models/contracts.py
> +        completion = self.env.ref(
```suggestion
        cancellation = self.env.ref(
```

2019-04-17 13:06 UTC, ecino commented on partner_communication_switzerland/models/contracts.py
> +        ).send_communication(completion, correspondent=False)
```suggestion
        ).send_communication(cancellation, correspondent=False)
```

2019-04-25 09:13 UTC, joblo-compassion commented
The cancellation communication was already fetch just above so I just change the communication used at the end

2019-04-25 12:16 UTC, ecino approved these changes

2019-04-25 12:17 UTC, merged