CO-2587 Salutation full name
CompassionCH/compassion-switzerland pull request #883
Opened 2019-05-21 12:18 UTC by joblo-compassion

2019-05-21 12:19 UTC, joblo-compassion commented
https://github.com/CompassionCH/compassion-modules/pull/1050

2019-05-23 09:50 UTC, ecino requested changes

2019-05-23 09:50 UTC, ecino commented on partner_communication_switzerland/models/res_partner.py
> +            p.informal_salutation = p.salutation
No, restore the original version.

2019-06-04 06:55 UTC, ecino approved these changes

2019-06-04 06:55 UTC, merged