CO-2519: Add buttons to print all medical/feedback surveys
CompassionCH/compassion-switzerland pull request #945
Opened 2019-10-17 09:41 UTC by Nooka10

2019-10-21 10:18 UTC, ecino commented
Some flake8/formatting issues:
```
website_event_compassion/models/event_event.py:92:27: E131 continuation line unaligned for hanging indent
website_event_compassion/models/event_event.py:93:35: E126 continuation line over-indented for hanging indent
website_event_compassion/models/event_event.py:93:89: E501 line too long (91 > 88 characters)
website_event_compassion/models/event_event.py:100:39: E127 continuation line over-indented for visual indent
website_event_compassion/models/event_event.py:100:89: E501 line too long (92 > 88 characters)
website_event_compassion/models/event_event.py:106:41: E127 continuation line over-indented for visual indent
website_event_compassion/models/event_event.py:106:89: E501 line too long (97 > 88 characters)
website_event_compassion/models/event_event.py:117:39: E127 continuation line over-indented for visual indent
website_event_compassion/models/event_event.py:117:89: E501 line too long (96 > 88 characters)
```

2019-10-31 08:35 UTC, ecino requested changes

2019-10-31 08:35 UTC, ecino commented on website_event_compassion/views/event_event_view.xml
> +                <button string="Print Medical Surveys" name="button_print_medical_surveys" type="object" class="oe_highlight" groups="base.group_user"/>
You added the button but the method is not defined anywhere! Did you forget to commit some files?

2019-10-31 15:43 UTC, Nooka10 commented on website_event_compassion/views/event_event_view.xml
> +                <button string="Print Medical Surveys" name="button_print_medical_surveys" type="object" class="oe_highlight" groups="base.group_user"/>
Oups. I erased them by error in the previous commit... -_-"

Corrected in #945

2019-11-01 07:21 UTC, ecino requested changes
Thanks! Here are some suggestions.

2019-11-01 07:21 UTC, ecino commented on website_event_compassion/models/event_event.py
> +        medical_survey_ids = self.compassion_event_id.registration_ids \
```suggestion
        medical_survey_ids = self.registration_ids \
```

2019-11-01 07:21 UTC, ecino commented on website_event_compassion/models/event_event.py
> +            .filtered(lambda p: p.state and p.state == 'done')
```suggestion
            .filtered(lambda p: p.state == 'done')
```

2019-11-01 07:21 UTC, ecino commented on website_event_compassion/models/event_event.py
> +            raise UserWarning('There is no medical survey to print')
```
from odoo.exceptions import UserError
from odoo import _
```
```suggestion
            raise UserError(_('There is no medical survey to print'))
```

2019-11-01 07:21 UTC, ecino commented on website_event_compassion/models/event_event.py
> +        feedback_survey_ids = self.compassion_event_id.registration_ids \
```suggestion
        feedback_survey_ids = self.registration_ids \
```

2019-11-01 07:21 UTC, ecino commented on website_event_compassion/models/event_event.py
> +            .filtered(lambda p: p.state and p.state == 'done')
```suggestion
            .filtered(lambda p: p.state == 'done')
```

2019-11-01 07:21 UTC, ecino commented on website_event_compassion/models/event_event.py
> +            raise UserWarning('There is no feedback survey to print')
```suggestion
            raise UserError(_('There is no feedback survey to print'))
```

2019-11-01 10:55 UTC, closed without merging