CO-2789: Fix multiple creation of "New Dossier" communication
CompassionCH/compassion-switzerland pull request #958
Opened 2019-10-29 14:03 UTC by Nooka10

2019-10-31 08:37 UTC, ecino commented
Please rebase on compassion/devel and remove unrelated commits. Fix lint issues and tests that are failing:
```
   File "/home/travis/build/CompassionCH/compassion-switzerland/partner_communication_switzerland/models/contracts.py", line 492, in contract_waiting
`     lambda c: 'S' in c.type and not c.is_active and c not in
`   File "/home/travis/build/CompassionCH/compassion-switzerland/partner_communication_switzerland/models/contracts.py", line 588, in _new_dossier
`     spo.send_communication(new_dossier)
`   File "/home/travis/build/CompassionCH/compassion-switzerland/partner_communication_switzerland/models/contracts.py", line 192, in send_communication
`     same_communication_search)
`   File "/home/travis/odoo-10.0/odoo/models.py", line 1516, in search
`     res = self._search(args, offset=offset, limit=limit, order=order, count=count)
`   File "/home/travis/odoo-10.0/odoo/models.py", line 4246, in _search
`     query = self._where_calc(args)
`   File "/home/travis/odoo-10.0/odoo/models.py", line 4040, in _where_calc
`     e = expression.expression(domain, self)
`   File "/home/travis/odoo-10.0/odoo/osv/expression.py", line 640, in __init__
`     self.expression = distribute_not(normalize_domain(domain))
`   File "/home/travis/odoo-10.0/odoo/osv/expression.py", line 289, in distribute_not
`     elif token in DOMAIN_OPERATORS_NEGATION:
` ValueError: <type 'exce
```

2019-11-01 08:05 UTC, ecino commented on partner_communication_switzerland/models/contracts.py
> -                    )
You removed your fix!

2019-11-01 08:06 UTC, ecino commented on partner_communication_switzerland/models/contracts.py
> +        csp = self.filtered(lambda s: 'CSP' in s.name)
This is a step back, it was on purpose changed to the above version. Please revert this change.

2019-11-01 08:07 UTC, ecino requested changes
Your last commit removed the purpose of this pull request :scream:

2019-11-01 08:24 UTC, Nooka10 commented on partner_communication_switzerland/models/contracts.py
> -                    )
Gosh... I need to sleep... -_-"

2019-11-01 11:15 UTC, closed without merging