CO-2791 and CO-2799: Add report 2BVR + fix BVR background
CompassionCH/compassion-switzerland pull request #964
Opened 2019-11-04 16:01 UTC by Nooka10

2019-11-05 15:59 UTC, ecino requested changes

2019-11-05 15:59 UTC, ecino commented on report_compassion/models/report_bvr_sponsorship.py
> +    def render_html(self, docids, data=None):
This method is not doing anything else than its parent, I think you can remove it.

2019-11-05 15:59 UTC, ecino commented on report_compassion/models/report_bvr_sponsorship_gift.py
> +    def render_html(self, docids, data=None):
This method is not doing anything else than its parent, you can remove it.

2019-11-05 15:59 UTC, ecino commented on report_compassion/report/bvr_sponsorship.xml
> +                        <t t-set="reference"
Missing margin? On other calls you have `<t t-set="margin" t-value="(date_index % 2) * 85"/>` but here you don't define it, is it on purpose?

2019-11-05 15:59 UTC, ecino commented on report_compassion/report/bvr_layout.xml
> -        <t t-set="margin" t-value="position * 0.2"/>
No margin now, is it correct?

2019-11-05 15:59 UTC, ecino commented on report_compassion/report/bvr_gift.xml
> -                <t t-set="position" t-value="((offset or 0) * product_index) % 3"/>
I think you should replace by a margin no? Something like this (don't know what 85 stands for) ?
`<t t-set="margin" t-value="(product_index % 3) * 85"/>`

2019-11-06 07:43 UTC, Nooka10 commented on report_compassion/report/bvr_sponsorship.xml
> +                        <t t-set="reference"
Margin is used only for the 2BVR. It's not needed for one or 3 BVR.
Do you prefer if I set margin = 0 on those calls?

2019-11-06 07:43 UTC, Nooka10 commented on report_compassion/report/bvr_sponsorship.xml
> +                        <t t-set="reference"
Margin is used only for the 2BVR. It's not needed for one or 3 BVR.
Do you prefer if I set margin = 0 on those calls?

2019-11-06 09:44 UTC, ecino requested changes
You had an unexpected paste of python code inside an xml, please fix that. Can you as well rebase your branch onto compassion/devel and keep only the relevant commits?

2019-11-06 09:44 UTC, ecino commented on report_compassion/report/bvr_sponsorship.xml
> +        <t t-set="o" t-# -*- coding: utf-8 -*-
You have something bad here.

2019-11-06 10:17 UTC, Nooka10 commented on report_compassion/report/bvr_sponsorship.xml
> +        <t t-set="o" t-# -*- coding: utf-8 -*-
Woups, corrected in #1a0aeba

2019-11-06 11:01 UTC, ecino approved these changes

2019-11-06 11:02 UTC, merged