CO-2946 applied same changes to welcome email
CompassionCH/compassion-switzerland pull request #984
Opened 2020-01-21 11:16 UTC by quentingigon

2020-01-21 11:53 UTC, quentingigon commented
Not yet tested

2020-01-24 13:13 UTC, ecino requested changes
This is not good in my opinion. You should try to understand why the method is called only with one record at the time and try to fix that instead, so that when it's called `self` is already the correct recordset (= all sponsorships that require the communication to be sent).

2020-01-28 08:57 UTC, quentingigon commented
The jobs are now executed once for all communications of each partner

2020-01-30 09:00 UTC, ecino approved these changes

2020-01-30 09:00 UTC, merged