CO-2994 Sponsorship switzerland migration v11
CompassionCH/compassion-switzerland pull request #988
Opened 2020-01-24 14:48 UTC by quentingigon

2020-02-10 14:45 UTC, quentingigon commented
I don't know where to specify the version of python modules for Travis

2020-02-18 09:01 UTC, quentingigon commented
I can't test the cancelling of a sponsorship because the US API used to make hold on children is not available until February the 21

2020-02-18 11:15 UTC, eicher31 requested changes

2020-02-18 11:15 UTC, eicher31 commented on sponsorship_switzerland/data/demo_journal.xml
> +<!--    </record>-->
Why comment this demo data?

2020-02-18 11:15 UTC, eicher31 commented on sponsorship_switzerland/models/completion_rules.py
> +    #     return res
To remove

2020-02-18 11:15 UTC, eicher31 commented on sponsorship_switzerland/models/contracts.py
> +        # today = datetime.today()
To remove if it's not necessary anymore!

2020-02-18 11:15 UTC, eicher31 commented on sponsorship_switzerland/models/contracts.py
> +        # inv_lines.mapped('invoice_id').cancel_payment_lines()
Same

2020-02-18 12:06 UTC, quentingigon commented on sponsorship_switzerland/models/contracts.py
> +        # today = datetime.today()
As I said, I can not test this feature so I let the old code there in case it's not working

2020-02-18 12:54 UTC, quentingigon commented on sponsorship_switzerland/data/demo_journal.xml
> +<!--    </record>-->
I dont know

2020-02-18 13:27 UTC, eicher31 approved these changes

2020-02-18 13:27 UTC, merged