CO-3029 Ne pas envoyer des reminders pour écrire à son filleul à ceux qui ont le tag "correspondance par compassion"
CompassionCH/compassion-switzerland pull request #997
Opened 2020-02-06 11:15 UTC by SylvainLosey

2020-02-20 13:13 UTC, ecino requested changes
`not in` supposes a list as the value I think.

2020-02-20 13:13 UTC, ecino commented on partner_communication_switzerland/models/contracts.py
> +             self.env.ref('partner_compassion.res_partner_category_corresp_compass').id)
```suggestion
             self.env.ref('partner_compassion.res_partner_category_corresp_compass').ids)
```

2020-02-21 14:10 UTC, ecino commented on partner_communication_switzerland/models/contracts.py
> +            self.env.ref('partner_compassion.res_partner_category_corresp_compass').ids)
```suggestion
                self.env.ref('partner_compassion.res_partner_category_corresp_compass').ids)
```

2020-02-25 08:42 UTC, SylvainLosey commented on partner_communication_switzerland/models/contracts.py
> +            self.env.ref('partner_compassion.res_partner_category_corresp_compass').ids)
Would go over character limit, created a variable instead

2020-02-26 13:44 UTC, ecino approved these changes

2020-02-26 13:45 UTC, merged